import { TrainingItem } from "../../../components/mind-dialog/training-status/training-status-tab";

// Mock data - replace with actual data fetching
export const mockTrainingItems: TrainingItem[] = [
  {
    id: "1",
    name: "This is a very long filename that should be truncated with ellipsis when it exceeds the container width.pdf",
    type: "PDF",
    trainedAt: new Date().toISOString(),
    status: "completed",
  },
  {
    id: "2",
    name: "Company Handbook.docx",
    type: "Document",
    trainedAt: new Date().toISOString(),
    status: "failed",
  },
  {
    id: "3",
    name: "Sales Training Manual.pdf",
    type: "PDF",
    trainedAt: new Date().toISOString(),
    status: "failed",
  },
  {
    id: "4",
    name: "Onboarding Guide.md",
    type: "Markdown",
    trainedAt: new Date().toISOString(),
    status: "completed",
  },
  {
    id: "5",
    name: "API Reference.md",
    type: "Markdown",
    trainedAt: new Date(Date.now() - 86400000).toISOString(),
    status: "failed",
  },
  {
    id: "6",
    name: "User Guide.pdf",
    type: "PDF",
    trainedAt: new Date(Date.now() - 86400000).toISOString(),
    status: "completed",
  },
  {
    id: "7",
    name: "Technical Specifications.docx",
    type: "Document",
    trainedAt: new Date(Date.now() - 86400000).toISOString(),
    status: "completed",
  },
  {
    id: "8",
    name: "Customer Support FAQ.txt",
    type: "Text",
    trainedAt: new Date(Date.now() - 86400000).toISOString(),
    status: "completed",
  },
  {
    id: "9",
    name: "Training Materials.zip",
    type: "Archive",
    trainedAt: new Date(Date.now() - 172800000).toISOString(),
    status: "queued",
  },
  {
    id: "10",
    name: "Knowledge Base.txt",
    type: "Text",
    trainedAt: new Date(Date.now() - 172800000).toISOString(),
    status: "completed",
  },
  {
    id: "11",
    name: "Developer Guide.pdf",
    type: "PDF",
    trainedAt: new Date(Date.now() - 172800000).toISOString(),
    status: "completed",
  },
  {
    id: "12",
    name: "Release Notes.md",
    type: "Markdown",
    trainedAt: new Date(Date.now() - 172800000).toISOString(),
    status: "failed",
  },
  {
    id: "13",
    name: "Security Policy.pdf",
    type: "PDF",
    trainedAt: new Date(Date.now() - 259200000).toISOString(),
    status: "completed",
  },
  {
    id: "14",
    name: "Code of Conduct.docx",
    type: "Document",
    trainedAt: new Date(Date.now() - 259200000).toISOString(),
    status: "completed",
  },
  {
    id: "15",
    name: "Best Practices Guide.md",
    type: "Markdown",
    trainedAt: new Date(Date.now() - 259200000).toISOString(),
    status: "completed",
  },
  {
    id: "16",
    name: "Architecture Diagrams.zip",
    type: "Archive",
    trainedAt: new Date(Date.now() - 345600000).toISOString(),
    status: "completed",
  },
  {
    id: "17",
    name: "Database Schema.txt",
    type: "Text",
    trainedAt: new Date(Date.now() - 345600000).toISOString(),
    status: "failed",
  },
  {
    id: "18",
    name: "Integration Guide.pdf",
    type: "PDF",
    trainedAt: new Date(Date.now() - 345600000).toISOString(),
    status: "completed",
  },
];
